export const data = [
	{ id: "1", name: "Anom", age: 19, gender: "Male" },
	{ id: "2", name: "Megha", age: 19, gender: "Female" },
	{ id: "3", name: "Subham", age: 25, gender: "Male" },
	{ id: "4", name: "Alex", age: 19, gender: "Male" },
	{ id: "5", name: "Mohana", age: 19, gender: "Female" },
	{ id: "6", name: "Nicky", age: 25, gender: "Male" },
	{ id: "7", name: "Justin", age: 19, gender: "Male" },
	{ id: "8", name: "Messi", age: 19, gender: "Female" },
	{ id: "9", name: "Ronaldo", age: 25, gender: "Male" },
	{ id: "10", name: "Salah", age: 19, gender: "Male" },
	{ id: "11", name: "Neymar", age: 19, gender: "Female" },
	{ id: "12", name: "Mpabe", age: 25, gender: "Male" },
	{ id: "13", name: "Ricky", age: 19, gender: "Male" },
	{ id: "14", name: "Andree", age: 19, gender: "Female" },
	{ id: "15", name: "Mike", age: 25, gender: "Male" },
]